### ISSUE TITLE
Issue with large text

### ISSUE THREAD

**Issue by vishal80072** [kontentino/react-multilevel-dropdown#10]
if the text of dropdown.item is large it is breaking the UI

**Comment by filippofilip95** [comment]
@vishal80072 Hi thanks for opening the issue :) 

How do you mean large text ? 

I've tried it wit long text and also with big font-size and it seems ok.

![Screenshot 2021-12-03 at 14 12 01](https://user-images.githubusercontent.com/10739349/144608336-4e84e76c-fbc7-43ac-b381-6c43e189ce2d.png)
![Screenshot 2021-12-03 at 14 13 54](https://user-images.githubusercontent.com/10739349/144608432-525300ee-9154-4ddd-808e-9fe14446891c.png)

Can you please provide us some examples/screenshot ? Thanks !

**Comment by patrikmasiar** [comment]
@vishal80072  As @filippofilip95 mentioned, it should not break the UI.

If the issue is the large width of the item, you can use your own class names or styles and add them to the component via props.

If anything, feel free to open a pull requests and contribute.

**Comment by vishal80072** [comment]
Yes actually I did it with word wrap and it worked for me Thanks for
response. 😊
