### ISSUE TITLE
Getting Compilation Error after installing and implementing module

### ISSUE THREAD

**Issue by imadityadi** [kontentino/react-multilevel-dropdown#16]
Compiled with problems:X

ERROR in ./node_modules/react-multilevel-dropdown/Dropdown.module.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[8].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[4]!./node_modules/react-multilevel-dropdown/Dropdown.module.scss)

Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\sass-loader\dist\utils.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\sass-loader\dist\index.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\sass-loader\dist\cjs.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\webpack\lib\NormalModule.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\webpack-manifest-plugin\dist\index.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\react-scripts\config\webpack.config.js
- C:\Users\Aadi\Desktop\quad\ecomadmin\node_modules\react-scripts\scripts\start.js

ERROR in ./node_modules/react-multilevel-dropdown/Dropdown.module.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[8].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[8].use[4]!./node_modules/react-multilevel-dropdown/Dropdown.module.scss)

Module build failed (from ./node_modules/resolve-url-loader/index.js):
TypeError: Cannot read properties of undefined (reading 'replace')

**Comment by patrikmasiar** [comment]
@imadityadi Thank you for reporting the issue. Could you provide us with more information about the environment you use?

**Comment by axelav** [comment]
Same issue - using with Create React App v5 and Node v16.

**Comment by nav-mohan** [comment]
`npm install sass` fixed the issue for me.
