### ISSUE TITLE
Possible to expose innerref of dropdown?

### ISSUE THREAD

**Issue by edlahoz** [kontentino/react-multilevel-dropdown#4]
Would like to enable onhover functionality for root level rather than just clicking to enable dropdown. As a quick fix, it might be worth exposing an innerref prop to tie to the ref of the dropdown itself in order to simulate a click from the consumer side.

**Comment by patrikmasiar** [comment]
@edlahoz You can update to version `2.0.0`. There you can refer to the dropdown button.

**Comment by patrikmasiar** [comment]
https://github.com/kontentino/react-multilevel-dropdown/commit/b45bb5aff4c2448ee55756ef4524aa8adb41eac3
