### ISSUE TITLE
How to get isOpen state in component?

### ISSUE THREAD

**Issue by nirvparekh** [kontentino/react-multilevel-dropdown#5]
Is there any way to get isOpen value? I need to toggle a css class on dropdown open/close.
```
<Dropdown>
  <Dropdown.Item></Dropdown.Item>
  <Dropdown.Item></Dropdown.Item>
  <Dropdown.Item></Dropdown.Item>
</Dropdown>
```

**Comment by MichalKowalczyk** [comment]
You can use the function below:
```
  const hideMenu = () => {
    var active = document.querySelector('[class*="Dropdown_active__"]') ?? false;
    if (active) active.click();
  };
```

Example usage:
```
    <MultiLevelMenu.Item onClick={hideMenu}>
       Lorem ipsum
    </MultiLevelMenu.Item>
```

If you don't want onClick in every MultiLevelMenu.Item, I'd suggest to create wrapper with onClick and children, example:

```
  const Item = ({ children }) => {
    return (
      <MultiLevelMenu.Item onClick={hideMenu}>
        {children}
      </MultiLevelMenu.Item>
    );
  };
```

**Comment by nirvparekh** [comment]
> You can use the function below:
> 
> ```
>   const hideMenu = () => {
>     var active = document.querySelector('[class*="Dropdown_active__"]') ?? false;
>     if (active) active.click();
>   };
> ```
> 
> Example usage:
> 
> ```
>   <MultiLevelMenu.Item onClick={hideMenu}>
>      Lorem ipsum
>   </MultiLevelMenu.Item>
> ```
> 
> If you don't want onClick in every MultiLevelMenu.Item, I'd suggest to create wrapper with onClick and children, example:
> 
> ```
>   const Item = ({ children }) => {
>     return (
>       <MultiLevelMenu.Item onClick={hideMenu}>
>         {children}
>       </MultiLevelMenu.Item>
>     );
>   };
> ```
> 
> ... and then:
> 
> ```
>   <Item>
>      Lorem ipsum
>   </Item>
> ```

This could be a patch workaround. Not a core solution.

**Comment by MichalKowalczyk** [comment]
> This could be a patch workaround. Not a core solution.

Ofc. it's just simple workaround. It should be labeled: "use at your own risk".

**Comment by filippofilip95** [comment]
Hey, guys thanks for opening the issue.

In new version we have added `isOpen` and `toggle` properties to the reference of dropdown.

You can now access it like this.

```js
export const CloseOnItemClick = () => {
    const ref = useRef(null);
    
    function onClick(e) {
        if (ref.current) {
            if (ref.current.isOpen) {
                ref.current.toggle(e);
            }
        }

        return (
            <UIDropdown title='Dropdown example' ref={ref}>
                <UIDropdown.Item onClick={onClick}>
                    Close on Click
                </UIDropdown.Item>
                 ... more code
```

**Comment by Daveiano** [comment]
Would be nice, if this could be added to the readme.
