### ISSUE TITLE
I want to open DropDown onMouseHover rather than onClick

### ISSUE THREAD

**Issue by rushifukat01** [kontentino/react-multilevel-dropdown#7]
I have DropDownItem inside DropDown when I click on DropDown Its subMenu is opening but I want it on onMouseHover
I want something like this 

<DropDown onMouseHover={()=> OpenDropDownItem}></DropDown>

 <Dropdown
              title={result.title}
              className={`dropDownContainer ${
                className === "fromCenter" && "fromCenter"
              }`}
            >
              {result.subMenu &&
                result.subMenu.map((subMenu, i) => (
                  <div key={i}>
                    <Dropdown.Item
                      className={`dropDownItem  ${
                        subMenu.title === "Support services"
                          ? "specificMenuScroll"
                          : ""
                      }`}
                    >
                      <a
                        href={subMenu.link ? subMenu.link : "#"}
                        target={subMenu.link && "_blank"}
                        rel={subMenu.link && "noreferrer"}
                      >
                        {subMenu.title}
                      </a>
                      {subMenu.subOptions && (
                        <Dropdown.Submenu position={position}>
                          {subMenu.subOptions.map((subOptions, index) => (
                            <Dropdown.Item
                              key={index}
                              className="dropDownSubMenuItem"
                            >
                              {/* {subOptions.link ? ( */}
                              <a
                                href={subOptions.link ? subOptions.link : "#"}
                                target={subOptions.link && "_blank"}
                                rel={subOptions.link && "noreferrer"}
                              >
                                {subOptions.linkName}
                              </a>
                              {/* ) : (
                                subOptions.linkName
                              )} */}
                            </Dropdown.Item>
                          ))}
                        </Dropdown.Submenu>
                      )}
                      {subMenu.subOptions && (
                        <Icon className="navigateIcon">navigate_next</Icon>
                      )}
                    </Dropdown.Item>
                  </div>
                ))}
            </Dropdown>

**Comment by swaranajan77** [comment]
I have also same issue, I want to open dropdownItem on hover of mouse in react multilevel dropdown

**Comment by filippofilip95** [comment]
Hello guys,

In new version `3.0.3` we have added new prop `openOnHover` 

```js
  return (
    <Dropdown openOnHover title={'Hello'}>    
```

This will open the dropdown on hover of mouse, however for closing dropdown you should still click outside or perform self closing of dropdown which is described here #6
